import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type {
  ClaudeCliClient,
  ClaudeCliInput,
  ClaudeCliResult,
  TailorResumeInput,
  ValidateAndCleanListingResult,
} from "./claude-cli";

/**
 * Dev-only scaffold (ticket 0.5) — NOT a user-facing feature. Fabricates the effects of a real
 * Claude Code CLI invocation (a judgment/response, plus any files a real run would write) so the
 * pipeline logic around it (queueing, progress reporting, file I/O) can be built and tested before
 * Phase 4 wires in the real CLI + Ollama integration.
 *
 * Callers deliberately exercise the "not a valid listing" branch (FR14) by including this marker
 * anywhere in the submitted text.
 */
export const STUB_NOT_A_LISTING_MARKER = "HUNTER_STUB_NOT_A_LISTING";

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function judgeAndCleanListing(
  listingText: string,
): Pick<ValidateAndCleanListingResult, "isValidListing" | "cleanedListingText"> {
  const trimmed = listingText.trim();
  if (trimmed.length === 0 || trimmed.includes(STUB_NOT_A_LISTING_MARKER)) {
    return { isValidListing: false, cleanedListingText: null };
  }
  return { isValidListing: true, cleanedListingText: trimmed.replace(/\s+/g, " ") };
}

function fabricateTailoredMarkdown(input: TailorResumeInput): string {
  const retryNote =
    input.attempt > 1
      ? `\n\n_Stub retry attempt ${input.attempt} — trim guidance: "${input.trimGuidance ?? "(none provided)"}"_`
      : "";
  return [
    "# Stubbed Tailored Resume",
    "",
    "_Generated by the HUNTER_MOCK_OLLAMA dev stub (server/src/claude-cli-stub.ts) — not real",
    "tailoring output. Source resume and listing content are not actually read/rewritten._",
    "",
    '## Listing excerpt this stub was "tailored" against',
    "",
    input.cleanedListingText.slice(0, 500),
    retryNote,
  ].join("\n");
}

function fabricateDocxPlaceholder(): string {
  return (
    "Stubbed .docx placeholder written by the HUNTER_MOCK_OLLAMA dev stub.\n" +
    "This is plain text, not a valid Word document — Phase 6 replaces this with a real " +
    ".docx writer derived from the source resume's style.\n"
  );
}

export function createStubClaudeCliClient(delayMs: number): ClaudeCliClient {
  return {
    async invoke(input: ClaudeCliInput): Promise<ClaudeCliResult> {
      if (delayMs > 0) {
        await sleep(delayMs);
      }

      if (input.stage === "validate-and-clean-listing") {
        const { isValidListing, cleanedListingText } = judgeAndCleanListing(input.listingText);
        return { stage: "validate-and-clean-listing", isValidListing, cleanedListingText };
      }

      mkdirSync(input.outputDir, { recursive: true });
      const markdownPath = join(input.outputDir, `${input.resumeBaseName}.md`);
      const docxPath = join(input.outputDir, `${input.resumeBaseName}.docx`);
      writeFileSync(markdownPath, fabricateTailoredMarkdown(input));
      writeFileSync(docxPath, fabricateDocxPlaceholder());
      return { stage: "tailor-resume", markdownPath, docxPath };
    },
  };
}
